baseURL = "https://inspiring-kilby-bb1bde.netlify.app/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-m10c-master"

[params]
[[params.menu]]
name = "About"
weight = 1
url = "https://inspiring-kilby-bb1bde.netlify.app/introduction/"

[[params.menu]]
name = "Annotated Definitions"
weight = 2
url = "https://inspiring-kilby-bb1bde.netlify.app/annotateddefinitions/"

[[params.menu]]
name = "Resource Guide"
weight = 3
url = "https://inspiring-kilby-bb1bde.netlify.app/resourceguide/"

[[params.menu]]
name = "Walkthrough"
weight = 4
url = "https://inspiring-kilby-bb1bde.netlify.app/walkthrough/"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"


